### ISSUE TITLE
Escape variables

### ISSUE THREAD

**Issue by ethlo** [thesimj/envyaml#14]
Thanks for this nice little library! I have the need to use `$.foo` as a value, and this gets picked up and attempted to be replaced with an env variable. Is there any way to escape variables? Thanks!

**Comment by thesimj** [comment]
Hi, hmm interesting request 🤔.  i will use $$ double dollar sign to escape variables, then this example
`test_escape: $$.foo` will give you a result as 
```python
env['test_escape']
>> $.foo
```

if this ok, then i will
