### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by bstivers** [thesimj/envyaml#26]
I'm getting the "EnvYAML require "pyyaml >= 5" module to work" error.
I've tried every version of pyyaml from 5.1 and up through the current 5.4.1.

Miniconda (py39) env. ```import yaml``` works as expected when loading the normal non-envyaml way.

**Comment by thesimj** [comment]
hi, just run install with update `pip install -U envyaml` and try library again.

this error means that inside library pyyaml you don't have a `safe_load` funstion
```
from yaml import safe_load
```
