### ISSUE TITLE
env.get('empty_env') returns '$NOT_EXIST_ENV_VARIABLE'

### ISSUE THREAD

**Issue by gabriel-msilva** [thesimj/envyaml#27]
From what I understood from the documentation, non-existing environment variables are not working as expected when `strict=False`.

`env.yaml` file:

```yaml
empty_env: $NOT_EXIST_ENV_VARIABLE
```

```python
from envyaml import EnvYAML

env = EnvYAML('env.yaml', strict=False)
print(env['empty_env'])
# >> $NOT_EXIST_ENV_VARIABLE
```

I was expecting it to return `None`.

```
python=3.7.10
envyaml=1.8.210417
```

**Comment by thesimj** [comment]
hi, in this case, it's better to return the original value `$NOT_EXIST_ENV_VARIABLE`. at least it will show what need to set,
