### ISSUE TITLE
Exclude `tests` folder from library

### ISSUE THREAD

**Issue by borgeser** [thesimj/envyaml#28]
Hello,

I've imported the `envyaml` module in my project.
When I browse my `.venv` folder I can see that a python module named `tests` is present. Inside, there is one file `test_envyaml.py`.

I suspect that the `setuptools` is not well configured in this project but I'm not a pro of this tool.

I've done this in my personal project, not sure if it's the best practice:

```
setup(
    name="...",
    ...
    packages=find_packages(exclude=["tests"])
)
```

**Comment by thesimj** [comment]
hi, sorry for the late response. good recommendation, let's do that.
