### ISSUE TITLE
Parsing fails with inline list

### ISSUE THREAD

**Issue by tonsV2** [thesimj/envyaml#9]
I had the below structure in a config file and the parsing 

```
mail:
    to: [ $HANDLERS_SMTP_TO ]
```

I get the following error
`ValueError: Strict mode enabled, variable $SMTP_HANDLER_TO] not defined!`

The below works just fine though

```
mail:
    to:
        - $HANDLERS_SMTP_TO
```

**Comment by thesimj** [comment]
Thanks you, good findings. fix will be soon.

**Comment by tonsV2** [comment]
Now the below fails

```
mail:
    to: [$SMTP_HANDLER_TO]
```

Are you doing the interpolation before the YAML parsing?
